# Generated by Django 4.2.4 on 2023-08-31 23:14

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import users.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=150, null=True)),
                ('profile_image', models.ImageField(blank=True, default='cover-book-quran.jpg', null=True, upload_to=users.models.get_file_path_profile)),
                ('descrption', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('profile_cover_image', models.ImageField(blank=True, default='cover-book-quran.jpg', null=True, upload_to=users.models.get_file_path_profile)),
                ('rating', models.IntegerField(blank=True, default=0, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('city', models.CharField(blank=True, max_length=150, null=True)),
                ('stats', models.CharField(blank=True, max_length=150, null=True)),
                ('ordered', models.IntegerField(blank=True, null=True)),
                ('conutry', models.CharField(blank=True, max_length=150, null=True)),
                ('pincode', models.CharField(blank=True, max_length=150, null=True)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('number_of_books', models.IntegerField(blank=True, default=0, null=True)),
                ('number_of_downloaded', models.IntegerField(blank=True, default=0, null=True)),
                ('number_of_read', models.IntegerField(blank=True, default=0, null=True)),
                ('web_site', models.URLField(blank=True, null=True)),
                ('contat_facebook', models.URLField(blank=True, null=True)),
                ('contat_twitter', models.URLField(blank=True, null=True)),
                ('number_of_gifft', models.IntegerField(default=0)),
                ('aprov', models.BooleanField(default=False)),
                ('pro', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
