# Generated by Django 4.2.4 on 2023-08-31 23:18

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pay_books',
            name='uuid',
            field=models.CharField(default=uuid.UUID('bd4f2f8f-4854-11ee-b263-3c970e3383cc'), max_length=200),
        ),
        migrations.AlterField(
            model_name='uplaod_free',
            name='uuid',
            field=models.CharField(default=uuid.UUID('bd4eba7a-4854-11ee-8de6-3c970e3383cc'), max_length=200),
        ),
    ]
