# Generated by Django 4.2.4 on 2023-08-31 23:25

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_alter_pay_books_uuid_alter_uplaod_free_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pay_books',
            name='uuid',
            field=models.CharField(default=uuid.UUID('a1d32370-4855-11ee-9ea4-3c970e3383cc'), max_length=200),
        ),
        migrations.AlterField(
            model_name='uplaod_free',
            name='uuid',
            field=models.CharField(default=uuid.UUID('a1d2fc61-4855-11ee-b657-3c970e3383cc'), max_length=200),
        ),
    ]
