# Generated by Django 4.2.5 on 2023-09-14 21:54

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_alter_pay_books_uuid_alter_uplaod_free_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pay_books',
            name='uuid',
            field=models.CharField(default=uuid.UUID('564f771a-5349-11ee-a7fc-96eea2ef5775'), max_length=200),
        ),
        migrations.AlterField(
            model_name='uplaod_free',
            name='uuid',
            field=models.CharField(default=uuid.UUID('564f2900-5349-11ee-a203-96eea2ef5775'), max_length=200),
        ),
    ]
