# Generated by Django 4.2.5 on 2023-09-16 05:34

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_alter_pay_books_uuid_alter_uplaod_free_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pay_books',
            name='uuid',
            field=models.CharField(default=uuid.UUID('ab2c32b7-5452-11ee-b0f2-9e92df0848ba'), max_length=200),
        ),
        migrations.AlterField(
            model_name='uplaod_free',
            name='uuid',
            field=models.CharField(default=uuid.UUID('ab2be493-5452-11ee-ad97-9e92df0848ba'), max_length=200),
        ),
    ]
