# Generated by Django 4.2.5 on 2023-09-30 22:05

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0006_alter_pay_books_uuid_alter_uplaod_free_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pay_books',
            name='uuid',
            field=models.CharField(default=uuid.UUID('7a08743b-5fdd-11ee-aff6-4a06766b6361'), max_length=200),
        ),
        migrations.AlterField(
            model_name='uplaod_free',
            name='uuid',
            field=models.CharField(default=uuid.UUID('7a08261a-5fdd-11ee-9d31-4a06766b6361'), max_length=200),
        ),
    ]
