# Generated by Django 4.2.5 on 2023-10-02 08:07

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0007_alter_pay_books_uuid_alter_uplaod_free_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pay_books',
            name='uuid',
            field=models.CharField(default=uuid.UUID('aabd3167-60fa-11ee-b9e8-a3ee520c5784'), max_length=200),
        ),
        migrations.AlterField(
            model_name='uplaod_free',
            name='uuid',
            field=models.CharField(default=uuid.UUID('aabd3166-60fa-11ee-b9e8-a3ee520c5784'), max_length=200),
        ),
    ]
