# Generated by Django 4.2.4 on 2023-08-31 23:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('books', '0002_alter_pay_books_uuid_alter_uplaod_free_uuid'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('publised', 'publised'), ('wiating', 'wiating'), ('draft', 'draft'), ('deleted', 'deleted')], default='wiating', max_length=10)),
                ('number_of_like', models.IntegerField(default=0)),
                ('number_of_deslike', models.IntegerField(default=0)),
                ('number_of_view', models.IntegerField(default=0)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.books')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.profile')),
            ],
        ),
    ]
