# Generated by Django 4.2.4 on 2023-08-31 23:18

from django.db import migrations, models
import tools.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CaruselImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=50, null=True)),
                ('caption', models.CharField(blank=True, max_length=255, null=True)),
                ('image', models.FileField(blank=True, default='whatsapp-icon.png', null=True, upload_to='upload/carusel')),
            ],
        ),
        migrations.CreateModel(
            name='LikePost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_id', models.CharField(max_length=500)),
                ('username', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Whatsapp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=True)),
                ('number', models.CharField(max_length=50)),
                ('message', models.TextField(max_length=500)),
                ('width', models.CharField(max_length=50)),
                ('heigth', models.CharField(max_length=50)),
                ('icon', models.ImageField(blank=True, default='assets/images/whatsapp-icon.png', null=True, upload_to=tools.models.get_file_path_image)),
            ],
        ),
    ]
